# Generated by Django 4.1.3 on 2022-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('bookid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('edition', models.CharField(max_length=10)),
            ],
        ),
    ]
