# Generated by Django 4.1.3 on 2022-11-24 13:50

from django.db import migrations, models
import validateapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=30, validators=[validateapp.validators.namelength]),
        ),
        migrations.AlterField(
            model_name='library',
            name='bname',
            field=models.CharField(max_length=40, validators=[validateapp.validators.namelength, validateapp.validators.firstletter]),
        ),
    ]
